### ISSUE TITLE
Add option to turn off trailing dot enforcing

### ISSUE THREAD

**Issue by juhosyrjanen** [octodns/octodns-route53#84] opened 2024-03-07 07:35 UTC
Hello!

By default OctoDNS is very particular about trailing dots in records to enforce unified syntax between DNS providers. Meanwhile, Route 53 assumes that the domain name is fully qualified. This means that Route 53 treats www.example.com (without a trailing dot) and www.example.com. (with a trailing dot) as identical.

This can be worked around by running `octodns-dump` with the `--lenient` flag, to dump all records into a OctoDNS file, fixing syntax issues and then running `octodns-sync`.

However, there is a ongoing issue in Route53 that causes the records not to be updated with the trailing dot. The record can be modified in AWS console or with OctoDNS to add the trailing dot, however this change is not applied on save/sync. Therefore OctoDNS tries to apply the trailing dots each run, failing.

In case the trailing dots are removed from OctoDNS config, and sync run the process will exit in the following error:
`octodns.record.exception.ValidationError: Invalid record`

AWS Support is aware of the issue at hand and are working on a fix from AWS side. Direct quote:

> -> I have checked internally and this is also a known issue to our team and they are working on a fix but there is also no ETA.
> 
> -> It was brought to the team's attention that via console updating existing records to have the trailing dot will not reflect as well as when using UPSERT for multiple CNAME records with trailing dot not all of them will reflect and have the dot. As seen here: [https://repost.aws/questions/QUj9pIHHnyRIGKNJqjqLgaZQ/questions/QUj9pIHHnyRIGKNJqjqLgaZQ/route53-batch-of-changes-succeeding-but-only-making-one-of-the-changes](https://repost.aws/questions/QUj9pIHHnyRIGKNJqjqLgaZQ/questions/QUj9pIHHnyRIGKNJqjqLgaZQ/route53-batch-of-changes-succeeding-but-only-making-one-of-the-changes) ?

I'm suggesting a feature to be added, where trailing period enforcing could be switched off for `octodns-route53` provider.  This would make OctoDNS a bit more flexible with Route53 given their stance on the record syntax.

**Comment by ross** [comment] 2024-03-07 15:03
As discussed over in https://github.com/octodns/octodns/issues/1146#issuecomment-1983693290 this isn't specific to Route53 and the solution is to fix the records, with a processor, so that they are in compliance with best practices and don't have the problem the best practice was intended to prevent.

Closing this, any further discussion can happen over in https://github.com/octodns/octodns/issues/1146

**Closed by ross** 2024-03-07 15:03 UTC

**Comment by juhosyrjanen** [comment] 2024-03-08 07:04
> As discussed over in [octodns/octodns#1146 (comment)](https://github.com/octodns/octodns/issues/1146#issuecomment-1983693290) this isn't specific to Route53 and the solution is to fix the records, with a processor, so that they are in compliance with best practices and don't have the problem the best practice was intended to prevent.
> 
> Closing this, any further discussion can happen over in [octodns/octodns#1146](https://github.com/octodns/octodns/issues/1146)

Very good, thank you and sorry for the duplicate issue!
